### ISSUE TITLE
求助，新建普通工程没有在BuildSettings里找到完整的User-Defines

### ISSUE THREAD

**Issue by liuzhiyi1992** [jackrex/FakeWeChatLoc#5]
完整的User-Dfines:
![image](https://cloud.githubusercontent.com/assets/13046550/18042980/61a0660e-6df7-11e6-8d7e-1ede6adf17e4.png)

新建普通工程target中的User-Defines:
![image](https://cloud.githubusercontent.com/assets/13046550/18043002/7d2a7f40-6df7-11e6-8088-0c8bf4e17c14.png)

**Comment by Iri-Y** [comment]
我的User-Defined也是有这样问题

**Comment by jackrex** [comment]
自己复制添加就行
